### ISSUE TITLE
ITEM condition not working?

### ISSUE THREAD

**Issue by NoComment1105** [Draylar/maybe-data#3]
Hi. I've been trying to use Maybe-Data to fix some errors that get produced with my recipes:
```shell
[03:34:42] [Worker-Main-7/ERROR]: Parsing error loading recipe deepslatecutting:deepslate_slab
com.google.gson.JsonSyntaxException: Unknown item 'deepslatecutting:deepslate_slab'
	at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[intermediary-server.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869.method_35228(class_1869.java:240) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:273) ~[intermediary-server.jar:?]
	at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:260) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_17720(class_1863.java:123) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_20705(class_1863.java:54) ~[intermediary-server.jar:?]
	at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[intermediary-server.jar:?]
	at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
	at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:568) [?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:710) [?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1769) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) [?:?]
```

And I tried to do so by adding maybe-data and using the ITEM tag to stop the recipe loading:

![image](https://user-images.githubusercontent.com/67918617/133211123-269365bf-45cf-40c5-9324-80e637497fd0.png)

![image](https://user-images.githubusercontent.com/67918617/133211214-fab82900-e097-4c15-99b3-6080d7c881a1.png)

Yet the initial error still occurs. I may be entirely wrong with how this mod works and those errors will still happen, and if so i apologise for taking up your time. Thanks

**Comment by NoComment1105** [comment]
am dumb
